# -*- coding: utf-8 -*-
"""
Central configuration: source path, constants, tolerances.
Do not hardcode these values anywhere else in the project.
"""
from pathlib import Path

# The workbook is READ-ONLY. Never write to this path.
# Portfolio/demo build: reads a fully synthetic workbook generated by
# scripts/generate_synthetic_data.py, resolved relative to this file so the
# project runs identically after a plain `git clone` on any machine - no
# dependency on a specific username, OneDrive, or any private company file.
# Regenerate with: python scripts/generate_synthetic_data.py
SOURCE_WORKBOOK = Path(__file__).parent / "data" / "sample_financial_data.xlsx"

SHEET_SALES = "المبيعات"
SHEET_SALES_RETURNS = "مردود المبيعات"
SHEET_PROFIT = "الارباح"
SHEET_FOREIGN_PURCHASES = "مشتريات خارجية"
SHEET_LOCAL_PURCHASES = "مشتريات داخلية"
SHEET_LOCAL_PURCHASE_RETURNS = "مردود المشتريات الداخلية"
SHEET_SUPPLIER_DEBT = "مديونية الموردين"
SHEET_SUPPLIER_CREDITORS = "دائنين الموردين"

CURRENCY_CODE = "SAR"

# Standard KSA VAT rate, used only as a reference for sanity checks -
# never assumed to override an actual reported tax amount.
STANDARD_VAT_RATE = 0.15

# Rounding tolerance (SAR) for reconciliation checks between reported and
# calculated monetary fields. Derived from Phase 1 findings: real reconciled
# rows differ by <1e-5 (float noise); genuine mismatches found in Phase 1
# were all > SAR 2. 0.05 cleanly separates float noise from real mismatches.
RECON_TOLERANCE = 0.05

# Foreign Purchases' purtot+addcost vs total is checked against a wider,
# explicitly separate tolerance than every other sheet, since freight/customs
# add-cost allocations can legitimately diverge more than a simple rounding
# tolerance would allow. Kept as its own constant so it is never confused
# with the tight RECON_TOLERANCE used elsewhere.
FOREIGN_PURCHASE_RECON_TOLERANCE = 15000.0

# Analysis period, confirmed present in full across all sheets in Phase 1.
PERIOD_START = "2022-01-01"
PERIOD_END = "2025-12-31"
ANALYSIS_YEARS = [2022, 2023, 2024, 2025]

# Generic walk-in / cash customer identity, confirmed in Phase 1
# (customer_no == 1 <-> customer name == 'نقدي', 100% consistent).
GENERIC_CASH_CUSTOMER_NO = 1
GENERIC_CASH_CUSTOMER_NAME = "نقدي"

# Generic/unspecified Local (Domestic) Purchases supplier bucket - a real
# production workbook may record some purchases under a literal supplier_name
# of 'عام' ("general") rather than a specific identifiable supplier. Excluded
# from identifiable Local Supplier concentration the same way 'نقدي' is
# excluded from customer concentration - it is not one real, identifiable
# supplier.
GENERIC_SUPPLIER_NAME = "عام"

# Sales Returns embedded grand-total row marker (Phase 1 finding).
SALES_RETURNS_TOTAL_ROW_MARKER = "اجمالى التقرير"

# Supplier Debt / Creditors embedded grand-total row marker (new-workbook finding).
SUPPLIER_BALANCE_TOTAL_ROW_MARKER = "الإجمالي"

# --------------------------------------------------------------------------
# Business calendar - Working Days (management request, new workbook update)
# --------------------------------------------------------------------------
# Friday is the only weekly non-working day assumed by this dashboard.
# Saturday, Saudi National Day, and any other public holiday are deliberately
# NOT subtracted unless management explicitly requests them later.
WEEKLY_NON_WORKING_DOW = {4}  # Monday=0 .. Sunday=6 (pandas dt.dayofweek) -> Friday=4

# Each Eid holiday block is a management-approved assumption of 7 consecutive
# calendar days beginning on the verified first day of Eid. Centralized here
# (not scattered through page code) so it can be adjusted later if management
# supplies company-specific holiday ranges.
EID_HOLIDAY_LENGTH_DAYS = 7

BUSINESS_HOLIDAYS = {
    2022: {"eid_fitr_start": "2022-05-02", "eid_adha_start": "2022-07-09"},
    2023: {"eid_fitr_start": "2023-04-21", "eid_adha_start": "2023-06-28"},
    2024: {"eid_fitr_start": "2024-04-10", "eid_adha_start": "2024-06-16"},
    2025: {"eid_fitr_start": "2025-03-30", "eid_adha_start": "2025-06-06"},
}
